"""Core module containing shared utilities and configurations."""

from .config import settings
from .error_codes import (
    CUSTOMER_EMAIL_ALREADY_EXISTS,
    CUSTOMER_NOT_FOUND,
    INSUFFICIENT_INVENTORY,
    INVALID_CUSTOMER_EMAIL,
    INVALID_CUSTOMER_PHONE,
    INVALID_ORDER_ITEMS,
    INVALID_PRODUCT_PRICE,
    INVALID_PRODUCT_QUANTITY,
    INVALID_REQUEST,
    INTERNAL_SERVER_ERROR,
    ORDER_NOT_FOUND,
    PRODUCT_NOT_FOUND,
    PRODUCT_SKU_ALREADY_EXISTS,
    VALIDATION_ERROR,
)
from .exception_handler import register_exception_handlers
from .exceptions import (
    AppException,
    CustomerEmailAlreadyExistsException,
    CustomerNotFoundException,
    InvalidCustomerEmailException,
    InvalidCustomerPhoneException,
    InvalidOrderItemsException,
    InvalidProductPriceException,
    InvalidProductQuantityException,
    OrderNotFoundException,
    ProductNotFoundException,
    ProductSKUAlreadyExistsException,
    InsufficientInventoryException,
)
from .response import (
    APIResponse,
    ErrorResponse,
    SuccessResponse,
    error_response,
    success_response,
)
from .status_codes import (
    HTTP_200_OK,
    HTTP_201_CREATED,
    HTTP_204_NO_CONTENT,
    HTTP_400_BAD_REQUEST,
    HTTP_404_NOT_FOUND,
    HTTP_409_CONFLICT,
    HTTP_422_UNPROCESSABLE_ENTITY,
    HTTP_500_INTERNAL_SERVER_ERROR,
)

__all__ = [
    "settings",
    "CUSTOMER_EMAIL_ALREADY_EXISTS",
    "CUSTOMER_NOT_FOUND",
    "INSUFFICIENT_INVENTORY",
    "INVALID_CUSTOMER_EMAIL",
    "INVALID_CUSTOMER_PHONE",
    "INVALID_ORDER_ITEMS",
    "INVALID_PRODUCT_PRICE",
    "INVALID_PRODUCT_QUANTITY",
    "INVALID_REQUEST",
    "INTERNAL_SERVER_ERROR",
    "ORDER_NOT_FOUND",
    "PRODUCT_NOT_FOUND",
    "PRODUCT_SKU_ALREADY_EXISTS",
    "VALIDATION_ERROR",
    "register_exception_handlers",
    "AppException",
    "CustomerEmailAlreadyExistsException",
    "CustomerNotFoundException",
    "InvalidCustomerEmailException",
    "InvalidCustomerPhoneException",
    "InvalidOrderItemsException",
    "InvalidProductPriceException",
    "InvalidProductQuantityException",
    "OrderNotFoundException",
    "ProductNotFoundException",
    "ProductSKUAlreadyExistsException",
    "InsufficientInventoryException",
    "APIResponse",
    "ErrorResponse",
    "SuccessResponse",
    "error_response",
    "success_response",
    "HTTP_200_OK",
    "HTTP_201_CREATED",
    "HTTP_204_NO_CONTENT",
    "HTTP_400_BAD_REQUEST",
    "HTTP_404_NOT_FOUND",
    "HTTP_409_CONFLICT",
    "HTTP_422_UNPROCESSABLE_ENTITY",
    "HTTP_500_INTERNAL_SERVER_ERROR",
]
