"""Custom error codes for API responses."""

# Product errors
PRODUCT_NOT_FOUND = "PRODUCT_NOT_FOUND"
PRODUCT_SKU_ALREADY_EXISTS = "PRODUCT_SKU_ALREADY_EXISTS"
INVALID_PRODUCT_PRICE = "INVALID_PRODUCT_PRICE"
INVALID_PRODUCT_QUANTITY = "INVALID_PRODUCT_QUANTITY"

# Customer errors
CUSTOMER_NOT_FOUND = "CUSTOMER_NOT_FOUND"
CUSTOMER_EMAIL_ALREADY_EXISTS = "CUSTOMER_EMAIL_ALREADY_EXISTS"
INVALID_CUSTOMER_EMAIL = "INVALID_CUSTOMER_EMAIL"
INVALID_CUSTOMER_PHONE = "INVALID_CUSTOMER_PHONE"

# Order errors
ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
INSUFFICIENT_INVENTORY = "INSUFFICIENT_INVENTORY"
INVALID_ORDER_ITEMS = "INVALID_ORDER_ITEMS"

# General errors
INVALID_REQUEST = "INVALID_REQUEST"
VALIDATION_ERROR = "VALIDATION_ERROR"
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
